### PR TITLE
Use semantic versioning

### PR DESCRIPTION
**Pull request by tbeu**

### CODE REVIEW

**Comment by sjoelund** [comment]
Note that according to the Modelica specification, the above changes make this sort as "no version number" (and thus something like loadModel(PlanarMechanics, version="1.4.0") would fail) :(

**Comment by tobolar** [comment]
So I suggest to refuse this pull request. Any other idea?

**Comment by tbeu** [comment]
Did you try if it fails?

**Comment by tobolar** [comment]
I have just tried and it seems to work - at least in Dymola.
The issue to discuss is that the version number changes its form from INTEGER to STRING then. No idea if this can be a problem.
I like semantic versioning but it is not really adopted by the Modelica Association. So from my point of view there is no reason to use it, except there will be a consent of the library maintainers.

**Comment by tbeu** [comment]
It also was a string before, basically the change is from "1.4.0 Dev Something" to "1.4.0-dev" to comply with semver, i.e. get rid of the blanks.

**Comment by tobolar** [comment]
@tbeu You are right, but what I want to say is the following:
According to current Modelica Specifications, 18.8.1 Version Numbering, the string "1.4.0-dev" will neither be the main release version nor pre-release version nor unordered version. This is because the version number can only start with
1. unsigned integer(s) followed by some character, both separated by _space_ in case of pre-release, or
2. non-digit character for unordered version. 

Additionally, according to the semantic versioning specification ([semver.org](http://semver.org/)), _... a pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers ..._ - see point 9. So I understand that paragraph as optional, not mandatory.

**Comment by tobolar** [comment]
Dear all,
I see no need to further discuss this issue now. Maybe once there will be an update in the Modelica Specification...

**Pull request closed without merging**
