### PR TITLE
Updated Library description to match library

### PR DESCRIPTION
**Pull request by fvanderlinden**

### CODE REVIEW

**Comment by tobolar** [comment]
Even better: A planar mechanICS library OR A library for planar mechanics OR A library for planar mechanism

**Comment by fvanderlinden** [comment]
I do not care so much what description the library has, the original description is simply not true anymore. @tobolar, can you implement what suits you the best?

**Comment by tbeu** [comment]
Well, remembering @dzimmer's talk back in 2012 in Fürstenfeldbruck, he said that the aim of the PlanarMechanics library is a simplification of the MSL MultiBody such that it can easier be used in education. As soon as visualizers were added the library is no longer simple but slightly bloated by this overhead. Is the library still used in education?

**Comment by johanrhodin** [comment]
My $.02:
- `Multibody` has the description `Library to model 3-dimensional mechanical systems`. I'd suggest  `Library to model 2-dimensional mechanical systems`
- Not that it really matters, but yes this library is used in education/academia (see http://rmc.dlr.de/sr/de/staff/dirk.zimmer/VirtualPhysics, but also at other universities including American universities)

**Comment by tobolar** [comment]
There are used following descriptions in the Modelica.Mechanics:
`Multibody`: `Library to model 3-dimensional mechanical systems`
`Rotational`: `Library to model 1-dimensional, rotational mechanical systems`
`Translational`: `Library to model 1-dimensional, translational mechanical systems`

Therfore I would prefer the suggestion of @johanrhodin with slight modification:
`Library to model 2-dimensional, planar mechanical systems`

**Comment by tobolar** [comment]
Based on this discussion, I've updated the description in 51ce745.

**Comment by tobolar** [comment]
Based on this discussion, I've updated the description in  51ce745 .

**Pull request closed without merging**
