### PR TITLE
- add missing inner World world to all examples

### PR DESCRIPTION
**Pull request by adrpo**

### CODE REVIEW

**Comment by fvanderlinden** [comment]
This is currently a bit of a problem coming from the new 3D coupling of the world. We hope to get this solved somehow so that in pure 2D models the 3D world is not needed. Until that I would not like to add these world models to the examples. Is this OK for you?

**Comment by adrpo** [comment]
Is fine. We could probably add a patch for OpenModelica or make it add the inner automatically (even if the specification say "a tool *may* add a missing inner".

**Comment by dzimmer** [comment]
Since the world model has no been reworked and there are two version, this pull-request is now outdated. Anyway, thanks for pointing on this issue.

**Comment by adrpo** [comment]
I made a patch for the library for our testing but I'll see if is still needed or not. Thanks!

**Pull request closed without merging**
